name: 'Google Cloud Storage Bucket Sync (GCP,GCS)'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: psaul20/gcs-bucket-sync-action-gcloud-storage@v.1
        with:
          secrets: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          bucket: 'website-bucket-20'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$|\.vscode/.*$|\.eslintrc.cjs$|\.prettierrc.json$'
          cache_control: 'no-cache'
