name: 'Google Cloud Storage Bucket Sync (GCP,GCS)'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'website-bucket-20'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
